### ISSUE TITLE
Ability to specify VM hardware version

### ISSUE THREAD

**Issue by mikepietruszka** [nmadhok/salt#16]
Hello,

Is there an ability to specify VM hardware version?  Such as vmx-08, vmx-09, vmx-10?  It seems that in some cases and environments it is necessary to use vmx-08 versus vmx-10.  It would be nice to be able to specify that in profiles or maps.

Thanks

**Comment by nmadhok** [comment]
@maschinetheist Thanks for your question. Right now, there's no ability to specify the VM hardware version but this is most definitely a feature we can add sometime soon. I will be working on adding the ability to specify VM hardware version soon.

**Comment by nmadhok** [comment]
@maschinetheist Would you prefer specifying ``hardware_version: 'vmx-09'`` or ``hardware_version: 9`` instead?

**Comment by nmadhok** [comment]
@maschinetheist The PR above adds the feature you requested. Feel free to try the patch and close the issue if everything's fine.

**Comment by mikepietruszka** [comment]
@nmadhok 

Looks good, I was able to specify version 9 and create a host with correct setting.

Thanks!
